### Import

In [1]:
from AgentDQNv1 import AgentDQNv1
from AgentDQNv2 import AgentDQNv2
from AgentDQNv3 import AgentDQNv3
from CounterAgent import CounterAgent

from envP4 import Connect4Env
import torch

### Load QValue/Net

In [2]:
first = True
qvalue1 = "Linear_Random_v3/20000_a1.pt"
qvalue2 = "Linear_Random_v3/20000_a2.pt"

### Play One-Step

In [3]:
#step
if first:
    
    player = 1
    winner = 0 #False

    env = Connect4Env()
    state = env.reset()
    agent = AgentDQNv2(1, env.action_space, env.observation_space, lr=0, eps_init=0, eps_step=0, name="player 1")
    agent2 = CounterAgent(2, env.action_space, env.observation_space, lr=0, eps_init=0, eps_step=0, name="player 2")
    # agent.q_values = torch.load("./runs/" + qvalue1)
    # agent2.q_values = torch.load("./runs/" + qvalue2)
    first = False
#try:
if not winner:
    if player == 1:
        action = agent.get_action(state, env.get_moves())
        print('agent1',action)
        state, reward, winner, info = env.step(action, player)
        player = 2
    elif player == 2:
        print("COUNTER")
        action = agent2.get_action(state, env.get_moves())
        print('agent2',action)
        state, reward, winner, info = env.step(action, player)
        player = 1

    env.render()

    if winner:
        print("THE WINNER IS PLAYER", winner)
        first = True
        winner = 0 #False



agent1 1
. . . . . . . 
. . . . . . . 
. . . . . . . 
. . . . . . . 
. . . . . . . 
. X . . . . . 


[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [4]:
prev_board_state = [[0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0],[0 ,0 ,0, 0, 0, 0],[0, 0, 0, 0, 0, 0],[0, 0 ,0, 0, 0, 0],[0, 0, 0, 0, 0 ,0],[0, 0 ,0 ,0, 0, 0]]
board_state      = [[0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0],[0 ,0 ,0, 0, 0, 0],[2, 0, 0, 0, 0, 0],[0, 0 ,0, 0, 0, 0],[0, 0, 0, 0, 0 ,0],[0, 0 ,0 ,0, 0, 0]]


In [5]:
"""import numpy as np

def agent_move(board_state, prev_board_state):
    # Convert input to NumPy arrays
    board_state = np.array(board_state)
    prev_board_state = np.array(prev_board_state)
    
    # Find the column where the opponent played
    diff = board_state - prev_board_state
    nonzero_idx = np.where(diff != 0)    
    if len(nonzero_idx[1]) > 0:
        opponent_last_move = (nonzero_idx[0][0],nonzero_idx[1][0])
    else:
        # If the difference is all zeros, assume opponent didn't make a move
        opponent_last_move = (-1,-1)
    
    action = opponent_last_move[0]
    return action 

    # Find the first empty cell in the column
    #col = opponent_last_move[0]
    #for row in range(0,board_state.shape[1]-1, 1):
        #if col >= 0 and board_state[col][row] == 0:
            #return (col,row)
"""

"import numpy as np\n\ndef agent_move(board_state, prev_board_state):\n    # Convert input to NumPy arrays\n    board_state = np.array(board_state)\n    prev_board_state = np.array(prev_board_state)\n    \n    # Find the column where the opponent played\n    diff = board_state - prev_board_state\n    nonzero_idx = np.where(diff != 0)    \n    if len(nonzero_idx[1]) > 0:\n        opponent_last_move = (nonzero_idx[0][0],nonzero_idx[1][0])\n    else:\n        # If the difference is all zeros, assume opponent didn't make a move\n        opponent_last_move = (-1,-1)\n    \n    action = opponent_last_move[0]\n    return action \n\n    # Find the first empty cell in the column\n    #col = opponent_last_move[0]\n    #for row in range(0,board_state.shape[1]-1, 1):\n        #if col >= 0 and board_state[col][row] == 0:\n            #return (col,row)\n"

In [6]:
"""agent_move(board_state, prev_board_state)"""

'agent_move(board_state, prev_board_state)'

In [7]:
[[0 for j in range(6)] for i in range(7)]

[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]